/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiHaBootstrapRouteImport } from './routes/api/ha/bootstrap'
import { Route as ApiHaLiveRouteImport } from './routes/api/ha/live'
import { Route as ApiHaStatesRouteImport } from './routes/api/ha/states'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHaBootstrapRoute = ApiHaBootstrapRouteImport.update({
  id: '/api/ha/bootstrap',
  path: '/api/ha/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHaLiveRoute = ApiHaLiveRouteImport.update({
  id: '/api/ha/live',
  path: '/api/ha/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHaStatesRoute = ApiHaStatesRouteImport.update({
  id: '/api/ha/states',
  path: '/api/ha/states',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/ha/bootstrap': typeof ApiHaBootstrapRoute
  '/api/ha/live': typeof ApiHaLiveRoute
  '/api/ha/states': typeof ApiHaStatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/ha/bootstrap': typeof ApiHaBootstrapRoute
  '/api/ha/live': typeof ApiHaLiveRoute
  '/api/ha/states': typeof ApiHaStatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/ha/bootstrap': typeof ApiHaBootstrapRoute
  '/api/ha/live': typeof ApiHaLiveRoute
  '/api/ha/states': typeof ApiHaStatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/login'
    | '/api/logout'
    | '/api/ha/bootstrap'
    | '/api/ha/live'
    | '/api/ha/states'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/login'
    | '/api/logout'
    | '/api/ha/bootstrap'
    | '/api/ha/live'
    | '/api/ha/states'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/login'
    | '/api/logout'
    | '/api/ha/bootstrap'
    | '/api/ha/live'
    | '/api/ha/states'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiHaBootstrapRoute: typeof ApiHaBootstrapRoute
  ApiHaLiveRoute: typeof ApiHaLiveRoute
  ApiHaStatesRoute: typeof ApiHaStatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ha/bootstrap': {
      id: '/api/ha/bootstrap'
      path: '/api/ha/bootstrap'
      fullPath: '/api/ha/bootstrap'
      preLoaderRoute: typeof ApiHaBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ha/live': {
      id: '/api/ha/live'
      path: '/api/ha/live'
      fullPath: '/api/ha/live'
      preLoaderRoute: typeof ApiHaLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ha/states': {
      id: '/api/ha/states'
      path: '/api/ha/states'
      fullPath: '/api/ha/states'
      preLoaderRoute: typeof ApiHaStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiHaBootstrapRoute: ApiHaBootstrapRoute,
  ApiHaLiveRoute: ApiHaLiveRoute,
  ApiHaStatesRoute: ApiHaStatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
